install.packages("testthat")
library(testthat)


data = read.csv(file = "path/to/searchData.csv") # file generated by louslist.org
dataLength = nrow(data)
shrunk = FALSE

test_that("length of CSV is cut", {
  remove()
  dataLength2 = nrow(data)
  if (dataLength2 < dataLength){
    shrunk = TRUE
  }
  expect_ture(shrunk)
})


test_that("adding building column", {
  buildingColumn()
  expect_match(name(classes$Building), "Building") 
})