install.packages("tm")
install.packages("devtools")
install.packages("roxygen2")
library(tm)
library(devtools, roxygen2)
devtools::create("studyspot")

data = read.csv(file = "/path/to/searchData.csv") # file generated by louslist.org
head(data$Room)
sort(table(data$Room))

# remove classes without classroom data
remove <- function(){
  tbd = data[data$Room == "TBA",]
  classes = data[data$Room != "TBA",]
  classes = subset (classes, select = -c(ClassNumber, Units, Title:Description))
}

remove()

# list of unique classrooms
classList <- unique(classes$Room)
classes$Room

buildingColumn <- function(){
  # add building to each class
  buildingList <- removeNumbers(classes$Room)
  classes$Building <- buildingList
}

buildingColumn()

# sort buildings by how many classes they hold
buildingListSort <- names(sort(table(buildingList), decreasing = TRUE))
buildingListSort

write.csv(buildingListSort, "D:\\path\\to\\uvabuildings.txt")
#write.csv(classes, "D:\\path\\to\\uvadata.csv")

