install.packages("tm")
library(tm)

data = read.csv(file = "path/to/searchData.csv") # file generated by louslist.org
head(data$Room)
sort(table(data$Room))

# remove classes without classroom data
tbd = data[data$Room == "TBA",]
classes = data[data$Room != "TBA",]
classes = subset (classes, select = -c(ClassNumber, Units, Title:Description))

# list of unique classrooms
classList <- unique(classes$Room)

# add building to each class
buildingList <- removeNumbers(classes$Room)
classes$Building <- buildingList

# sort buildings by how many classes they hold
buildingListSort <- names(sort(table(buildingList), decreasing = TRUE))
buildingListSort

write.csv(buildingListSort, "D:\\path\\to\\uvabuildings.txt")
write.csv(classes, "D:\\path\\to\\uvadata.csv")
